return {
  -- Paarthurnax
  {
    quote = "What is better - to be born good, or to overcome your evil nature through great effort?",
    author = "Paarthurnax",
  },
  { quote = "Dovahkiin. You have tasted the Voice of the Graybeards and passed through.", author = "Paarthurnax" },
  { quote = "The Blades are wise not to trust me. Only Paarthurnax has overlooked my crime.", author = "Paarthurnax" },
  { quote = "Do you have the courage to face the World-Eater, Dragonborn?", author = "Paarthurnax" },
  { quote = "The elder scrolls... such power, such knowledge.", author = "Paarthurnax" },
  { quote = "Alduin's hunger will consume all, but you have the strength to resist.", author = "Paarthurnax" },
  { quote = "I am not proud of what I did. It was necessary.", author = "Paarthurnax" },
  { quote = "This world is in flux, but you, Dovahkiin, can direct its course.", author = "Paarthurnax" },
  { quote = "Even I must concede the power of the Voice when wielded by a true Dragonborn.", author = "Paarthurnax" },
  { quote = "Is it not enough that I have lived for thousands of years, trying to atone?", author = "Paarthurnax" },
  { quote = "Your Thu'um is strong, Dragonborn. It echoes through time.", author = "Paarthurnax" },
  { quote = "The Way of the Voice is a path of understanding and reflection.", author = "Paarthurnax" },
  { quote = "The World-Eater fears you, Dovahkiin. You are his only true equal.", author = "Paarthurnax" },
  { quote = "Time is ever-flowing, like the river. It cannot be changed but can be guided.", author = "Paarthurnax" },
  { quote = "Victory will be ours, if you stand strong, Dovahkiin.", author = "Paarthurnax" },
  { quote = "I seek only to teach others the path of balance, the Way of the Voice.", author = "Paarthurnax" },
  { quote = "The Voice is a gift. It is a window into our true nature.", author = "Paarthurnax" },
  { quote = "Alduin cannot be allowed to devour the world. You are our hope.", author = "Paarthurnax" },
  {
    quote = "It is the nature of dragons to dominate. But I have learned to temper that desire.",
    author = "Paarthurnax",
  },
  { quote = "A shout can alter the course of fate, but it must be wielded wisely.", author = "Paarthurnax" },

  -- Delphine
  { quote = "You’re either the bravest person I’ve ever met, or the biggest fool.", author = "Delphine" },
  { quote = "We’re here to stop the dragons, if it’s not too late.", author = "Delphine" },
  { quote = "I’ve been looking for someone like you.", author = "Delphine" },
  { quote = "The Blades have always defended the Dragonborn. It is time you defended us.", author = "Delphine" },
  { quote = "The Thalmor are just as much of a threat as the dragons.", author = "Delphine" },
  { quote = "Killing dragons is a serious business. You’d better be ready.", author = "Delphine" },
  { quote = "We’re going to rebuild the Blades. You’re the first recruit.", author = "Delphine" },
  { quote = "You’ve done it, Dragonborn. The Greybeards were right about you.", author = "Delphine" },
  { quote = "Don’t trust anyone. Especially the Thalmor.", author = "Delphine" },
  { quote = "The Blades must rise again. Will you stand with us?", author = "Delphine" },
  { quote = "Dragons aren’t just coming back. They’re coming back to life.", author = "Delphine" },
  { quote = "I don’t trust Paarthurnax. Dragons cannot change their nature.", author = "Delphine" },
  { quote = "Killing Alduin is the only way to truly stop the dragons.", author = "Delphine" },
  { quote = "This war, it’s just a distraction. The dragons are the real threat.", author = "Delphine" },
  { quote = "We’ve got to stop them. Before it’s too late.", author = "Delphine" },
  { quote = "The Blades have always been the defenders of the Dragonborn.", author = "Delphine" },
  { quote = "You need to decide who your allies are, Dragonborn.", author = "Delphine" },
  { quote = "Alduin’s return was predicted in ancient prophecy.", author = "Delphine" },
  { quote = "Our cause is righteous. The Blades will fight until the end.", author = "Delphine" },
  { quote = "The world is on the brink of destruction, and it’s up to you to stop it.", author = "Delphine" },

  -- Ulfric Stormcloak
  { quote = "I fight for the men I’ve held in my arms, dying on foreign soil.", author = "Ulfric Stormcloak" },
  { quote = "Only the strong can rule in Skyrim.", author = "Ulfric Stormcloak" },
  { quote = "Skyrim belongs to the Nords!", author = "Ulfric Stormcloak" },
  { quote = "I fight for my people, and for their freedom.", author = "Ulfric Stormcloak" },
  { quote = "Talos be with you.", author = "Ulfric Stormcloak" },
  { quote = "We’ve driven the Empire out of Skyrim, but the war is far from over.", author = "Ulfric Stormcloak" },
  { quote = "I will die before I allow Skyrim to fall into the hands of the Empire.", author = "Ulfric Stormcloak" },
  { quote = "The Empire has no place in Skyrim. We will drive them out.", author = "Ulfric Stormcloak" },
  { quote = "We fight for freedom. We fight for Skyrim.", author = "Ulfric Stormcloak" },
  { quote = "The Nords are the true sons and daughters of Skyrim.", author = "Ulfric Stormcloak" },
  { quote = "We will reclaim our homeland, whatever the cost.", author = "Ulfric Stormcloak" },
  { quote = "Our fight is for the future of Skyrim.", author = "Ulfric Stormcloak" },
  { quote = "This is the land of the Nords. We will defend it.", author = "Ulfric Stormcloak" },
  { quote = "Our ancestors fought for Skyrim, and so will we.", author = "Ulfric Stormcloak" },
  { quote = "I am the rightful High King of Skyrim.", author = "Ulfric Stormcloak" },
  { quote = "The Empire will fall, and Skyrim will rise.", author = "Ulfric Stormcloak" },
  { quote = "The Empire has betrayed us, and we will not forgive them.", author = "Ulfric Stormcloak" },
  { quote = "The blood of our ancestors runs through our veins. We will prevail.", author = "Ulfric Stormcloak" },
  { quote = "Skyrim will be free. We will see to it.", author = "Ulfric Stormcloak" },
  { quote = "Talos guide us, for we fight in his name.", author = "Ulfric Stormcloak" },

  -- General Tullius
  { quote = "And so you stand before me, a hero of the Empire, a traitor to the crown.", author = "General Tullius" },
  { quote = "I breathe now in royalty, and reshape this land which is mine.", author = "General Tullius" },
  { quote = "The Empire is what’s keeping Skyrim from tearing itself apart.", author = "General Tullius" },
  { quote = "Ulfric will pay for his crimes against the Empire.", author = "General Tullius" },
  { quote = "This rebellion must be quashed, once and for all.", author = "General Tullius" },
  {
    quote = "The Stormcloaks are nothing more than rebels, trying to break away from the Empire.",
    author = "General Tullius",
  },
  { quote = "The Emperor will not tolerate this rebellion any longer.", author = "General Tullius" },
  { quote = "Skyrim is an integral part of the Empire. We cannot afford to lose it.", author = "General Tullius" },
  {
    quote = "This war is about more than just Skyrim. It’s about the future of the Empire.",
    author = "General Tullius",
  },
  { quote = "The Thalmor would love to see Skyrim break away from the Empire.", author = "General Tullius" },
  { quote = "We’ve fought too long and too hard to let Skyrim fall to the Stormcloaks.", author = "General Tullius" },
  { quote = "Ulfric is a traitor to the Empire, and must be brought to justice.", author = "General Tullius" },
  { quote = "The Empire has stood for centuries. It will not fall now.", author = "General Tullius" },
  { quote = "This rebellion is a stain on the Empire, and we will wipe it clean.", author = "General Tullius" },
  { quote = "I serve the Empire, and I will see it through to the end.", author = "General Tullius" },
  { quote = "The future of Skyrim depends on the Empire.", author = "General Tullius" },
  { quote = "We must crush the Stormcloaks, for the good of the Empire.", author = "General Tullius" },
  { quote = "Skyrim is stronger within the Empire, not outside it.", author = "General Tullius" },
  { quote = "The Emperor has entrusted me with the task of ending this rebellion.", author = "General Tullius" },
  { quote = "We will bring peace to Skyrim, no matter the cost.", author = "General Tullius" },

  -- Arngeir
  { quote = "Trust in me, Dragonborn. Trust in the Voice.", author = "Arngeir" },
  { quote = "The Way of the Voice leads to mastery of the self.", author = "Arngeir" },
  { quote = "You must learn the Voice as you learn the Thu'um.", author = "Arngeir" },
  {
    quote = "The Voice is a gift from the gods, but it must be earned through study and discipline.",
    author = "Arngeir",
  },
  { quote = "Your path is clear, Dragonborn. You must learn the Way of the Voice.", author = "Arngeir" },
  { quote = "The Greybeards have long been the keepers of the Voice.", author = "Arngeir" },
  { quote = "The Thu'um is a powerful tool, but it must be used with wisdom.", author = "Arngeir" },
  { quote = "The Voice is a gift, but it is also a responsibility.", author = "Arngeir" },
  { quote = "The Greybeards have spent centuries mastering the Voice.", author = "Arngeir" },
  { quote = "A shout is a powerful weapon, but it can also be a burden.", author = "Arngeir" },
  { quote = "The path of the Voice is not an easy one, but it is the only true way.", author = "Arngeir" },
  { quote = "The Greybeards will guide you on your journey, but you must walk the path yourself.", author = "Arngeir" },
  { quote = "The Voice is not just a weapon. It is a reflection of the soul.", author = "Arngeir" },
  { quote = "The power of the Voice is not to be taken lightly, Dragonborn.", author = "Arngeir" },
  { quote = "Your destiny lies in the mastery of the Voice.", author = "Arngeir" },
  { quote = "The Thu'um can move mountains, but it can also bring peace.", author = "Arngeir" },
  { quote = "The Greybeards have spent their lives seeking to understand the Voice.", author = "Arngeir" },
  { quote = "The power of the Voice must be tempered with wisdom.", author = "Arngeir" },
  { quote = "The Way of the Voice is the path to mastery of the self.", author = "Arngeir" },
  { quote = "The Voice is a gift from the gods, but it must be earned.", author = "Arngeir" },

  -- Astrid
  { quote = "We are all bound to our fates.", author = "Astrid" },
  { quote = "Welcome to the Dark Brotherhood.", author = "Astrid" },
  { quote = "There's no turning back now.", author = "Astrid" },
  { quote = "We don't kill for the coin. We kill for the Brotherhood.", author = "Astrid" },
  { quote = "To be a part of the Dark Brotherhood is to embrace death.", author = "Astrid" },
  { quote = "The Night Mother is our guide.", author = "Astrid" },
  { quote = "Do you want to live, or do you want to die?", author = "Astrid" },
  { quote = "Every death is a story. Every story has a purpose.", author = "Astrid" },
  { quote = "You will learn the ways of the Brotherhood.", author = "Astrid" },
  { quote = "Life is for the living. We embrace the shadows.", author = "Astrid" },
  { quote = "We have a contract, and contracts must be fulfilled.", author = "Astrid" },
  { quote = "You will learn to accept death as a way of life.", author = "Astrid" },
  { quote = "Our enemies are everywhere. Trust no one.", author = "Astrid" },
  { quote = "I trust you, and I expect you to trust me.", author = "Astrid" },
  { quote = "We all have our pasts, but we can shape our futures.", author = "Astrid" },
  { quote = "The Dark Brotherhood is a family, and family looks out for one another.", author = "Astrid" },
  { quote = "We are more than just assassins. We are an order.", author = "Astrid" },
  { quote = "You must prove your loyalty to the Brotherhood.", author = "Astrid" },
  { quote = "Fear is a powerful tool. Use it wisely.", author = "Astrid" },
  { quote = "The Night Mother watches over us.", author = "Astrid" },
  { quote = "The bonds we share are stronger than blood.", author = "Astrid" },

  -- Aela the Huntress
  { quote = "The hunt is more than just a sport. It's a way of life.", author = "Aela the Huntress" },
  { quote = "I trust you, but I still want to see you prove yourself.", author = "Aela the Huntress" },
  { quote = "We are all werewolves. We embrace our true selves.", author = "Aela the Huntress" },
  { quote = "The world is full of prey, and it is our duty to hunt.", author = "Aela the Huntress" },
  { quote = "Our instincts guide us. Trust them.", author = "Aela the Huntress" },
  { quote = "The Circle has a responsibility to the pack.", author = "Aela the Huntress" },
  { quote = "Strength is in unity. We stand together, always.", author = "Aela the Huntress" },
  { quote = "You have a special connection to the hunt. Embrace it.", author = "Aela the Huntress" },
  { quote = "Hunting is a way to understand the world around us.", author = "Aela the Huntress" },
  { quote = "We fight for the Companions and for each other.", author = "Aela the Huntress" },
  { quote = "Our bond as werewolves makes us stronger.", author = "Aela the Huntress" },
  { quote = "To be a Companion is to live for the hunt.", author = "Aela the Huntress" },
  { quote = "You can’t let fear control you. Embrace your power.", author = "Aela the Huntress" },
  { quote = "The moon guides our path. Follow its light.", author = "Aela the Huntress" },
  { quote = "The thrill of the hunt is what makes life worth living.", author = "Aela the Huntress" },
  { quote = "We share a common bond. We are all warriors.", author = "Aela the Huntress" },
  { quote = "The hunt is in our blood. Never forget it.", author = "Aela the Huntress" },
  { quote = "We are more than just warriors. We are family.", author = "Aela the Huntress" },
  { quote = "Embrace the wolf within. It makes you who you are.", author = "Aela the Huntress" },
  { quote = "We will never back down. We are Companions.", author = "Aela the Huntress" },

  -- Lydia
  { quote = "I will protect you with my life.", author = "Lydia" },
  { quote = "We have to stay sharp. Danger is everywhere.", author = "Lydia" },
  { quote = "I’m sworn to carry your burdens.", author = "Lydia" },
  { quote = "Lead on, and I will follow.", author = "Lydia" },
  { quote = "My sword is yours to command.", author = "Lydia" },
  { quote = "I will guard you, my Thane.", author = "Lydia" },
  { quote = "We will face any challenge together.", author = "Lydia" },
  { quote = "Your enemies are my enemies.", author = "Lydia" },
  { quote = "We cannot afford to lose focus. Stay vigilant.", author = "Lydia" },
  { quote = "I will always be by your side.", author = "Lydia" },
  { quote = "Together, we are unstoppable.", author = "Lydia" },
  { quote = "You have my loyalty, Thane.", author = "Lydia" },
  { quote = "Let’s make our enemies regret underestimating us.", author = "Lydia" },
  { quote = "Our journey is just beginning.", author = "Lydia" },
  { quote = "I’m ready to fight, if you are.", author = "Lydia" },
  { quote = "Lead the way, and I will follow.", author = "Lydia" },
  { quote = "I have your back, no matter what.", author = "Lydia" },
  { quote = "I will defend you until my last breath.", author = "Lydia" },
  { quote = "You are a true hero, Thane.", author = "Lydia" },
  { quote = "Let’s face whatever comes next together.", author = "Lydia" },
  { quote = "I’ll always be here for you.", author = "Lydia" },

  -- Serana
  { quote = "I didn’t ask for this. I just want to be free.", author = "Serana" },
  { quote = "You’re not like the others. You can handle this.", author = "Serana" },
  { quote = "We need to find a way to stop them.", author = "Serana" },
  { quote = "I know what it’s like to feel trapped.", author = "Serana" },
  { quote = "This is more than just a fight for survival.", author = "Serana" },
  { quote = "You’re stronger than you think.", author = "Serana" },
  { quote = "I will help you fight against them.", author = "Serana" },
  { quote = "My blood is a curse, but it’s also a weapon.", author = "Serana" },
  { quote = "I’ve seen horrors that would make your skin crawl.", author = "Serana" },
  { quote = "We can break the cycle, together.", author = "Serana" },
  { quote = "There’s always a way out, if you’re willing to fight for it.", author = "Serana" },
  { quote = "I may not look it, but I can handle myself.", author = "Serana" },
  { quote = "We are not alone in this fight.", author = "Serana" },
  { quote = "I can feel the darkness creeping in. We must act fast.", author = "Serana" },
  { quote = "Our destinies are intertwined. We have to work together.", author = "Serana" },
  { quote = "The past is a heavy burden to bear.", author = "Serana" },
  { quote = "Sometimes, the greatest power lies in what you resist.", author = "Serana" },
  { quote = "I can’t go back to the way things were. I don’t want to.", author = "Serana" },
  { quote = "This world is full of shadows. We must navigate them carefully.", author = "Serana" },
  { quote = "Hope is not lost. We can find a way forward.", author = "Serana" },
  { quote = "I won’t let fear dictate my life anymore.", author = "Serana" },

  -- Jarl Balgruuf
  { quote = "We are all bound to our fates.", author = "Jarl Balgruuf" },
  { quote = "A strong leader is what Skyrim needs.", author = "Jarl Balgruuf" },
  { quote = "Let me tell you, being Jarl is not easy.", author = "Jarl Balgruuf" },
  { quote = "The dragons are a threat to us all.", author = "Jarl Balgruuf" },
  { quote = "We must come together to face this danger.", author = "Jarl Balgruuf" },
  { quote = "I would have your counsel, not your opinion.", author = "Jarl Balgruuf" },
  { quote = "The people of Whiterun are counting on us.", author = "Jarl Balgruuf" },
  { quote = "In times of war, we must stand united.", author = "Jarl Balgruuf" },
  { quote = "I expect you to be loyal to the cause.", author = "Jarl Balgruuf" },
  { quote = "We are all Nords. We should stand together.", author = "Jarl Balgruuf" },
  { quote = "The threats we face are greater than ever before.", author = "Jarl Balgruuf" },
  { quote = "The Stormcloak rebellion is tearing Skyrim apart.", author = "Jarl Balgruuf" },
  { quote = "I will not let my people fall into chaos.", author = "Jarl Balgruuf" },
  { quote = "We need strength and wisdom to lead us through these times.", author = "Jarl Balgruuf" },
  { quote = "I have seen what happens when we let fear control us.", author = "Jarl Balgruuf" },
  { quote = "Every decision I make is for the good of my people.", author = "Jarl Balgruuf" },
  { quote = "Do not underestimate the power of unity.", author = "Jarl Balgruuf" },
  { quote = "The future of Skyrim is in our hands.", author = "Jarl Balgruuf" },
  { quote = "We must put aside our differences for the greater good.", author = "Jarl Balgruuf" },
  { quote = "Your actions today will shape our tomorrow.", author = "Jarl Balgruuf" },
  { quote = "I will always fight for the people of Whiterun.", author = "Jarl Balgruuf" },

  -- Mercer Frey
  { quote = "You’re not the only one with a desire for power.", author = "Mercer Frey" },
  { quote = "The Thieves Guild is mine to command.", author = "Mercer Frey" },
  { quote = "We’re not in the business of honesty.", author = "Mercer Frey" },
  { quote = "Power is the only thing that matters.", author = "Mercer Frey" },
  { quote = "You’ve made a grave mistake by crossing me.", author = "Mercer Frey" },
  { quote = "The Guild is what I make it.", author = "Mercer Frey" },
  { quote = "You can’t trust anyone in this business.", author = "Mercer Frey" },
  { quote = "I will do whatever it takes to stay on top.", author = "Mercer Frey" },
  { quote = "Trust is a luxury we cannot afford.", author = "Mercer Frey" },
  { quote = "The world is a dark place, and I intend to thrive in it.", author = "Mercer Frey" },
  { quote = "We don’t have friends; we have associates.", author = "Mercer Frey" },
  { quote = "You think you can stop me? You’re a fool.", author = "Mercer Frey" },
  { quote = "The Guild is mine to shape as I see fit.", author = "Mercer Frey" },
  { quote = "Loyalty is for the weak.", author = "Mercer Frey" },
  { quote = "I will get what I want, one way or another.", author = "Mercer Frey" },
  { quote = "The Thieves Guild has been corrupted, and it’s my job to fix it.", author = "Mercer Frey" },
  { quote = "I don’t need anyone’s help to get what I want.", author = "Mercer Frey" },
  { quote = "I have eyes and ears everywhere.", author = "Mercer Frey" },
  { quote = "You will regret standing in my way.", author = "Mercer Frey" },
  { quote = "You can’t fight fate, my friend.", author = "Mercer Frey" },

  -- Esbern
  { quote = "You have no idea what the dragons are capable of.", author = "Esbern" },
  { quote = "The history of the dragons is written in blood.", author = "Esbern" },
  { quote = "You’re not ready for the truth about the dragons.", author = "Esbern" },
  { quote = "We’ve been fighting this war for a long time.", author = "Esbern" },
  { quote = "The time for hiding is over.", author = "Esbern" },
  { quote = "You must learn the ancient ways to fight the dragons.", author = "Esbern" },
  { quote = "The dragons are coming back, and we must be ready.", author = "Esbern" },
  { quote = "You are the last hope for Tamriel.", author = "Esbern" },
  { quote = "We need to gather allies for the coming storm.", author = "Esbern" },
  { quote = "You must harness the power of the Thu'um.", author = "Esbern" },
  { quote = "Knowledge is our greatest weapon against the dragons.", author = "Esbern" },
  { quote = "The history of the dragons is vital to our survival.", author = "Esbern" },
  { quote = "There is much to learn, and little time to do it.", author = "Esbern" },
  { quote = "Your destiny is intertwined with the dragons.", author = "Esbern" },
  { quote = "The dragons may be powerful, but we have knowledge.", author = "Esbern" },
  { quote = "Time is of the essence. We must act now.", author = "Esbern" },
  { quote = "The dragons’ return is a sign of darker times ahead.", author = "Esbern" },
  { quote = "We need to find the truth behind the dragons’ resurgence.", author = "Esbern" },
  { quote = "You must trust your instincts as a Dragonborn.", author = "Esbern" },
  { quote = "Prepare yourself for the trials that lie ahead.", author = "Esbern" },
  { quote = "The past holds the key to our future.", author = "Esbern" },

  -- Alduin
  { quote = "I am the first, and the last. I am the guardian of the world.", author = "Alduin" },
  { quote = "You cannot escape your destiny.", author = "Alduin" },
  { quote = "I will devour the world and rise again!", author = "Alduin" },
  { quote = "You are nothing but a puppet, and I am the master.", author = "Alduin" },
  { quote = "Your will is weak; your soul is mine!", author = "Alduin" },
  { quote = "I am the god of destruction and rebirth.", author = "Alduin" },
  { quote = "I have conquered all, and I will conquer you.", author = "Alduin" },
  { quote = "You cannot hope to defeat me!", author = "Alduin" },
  { quote = "Foolish mortals, you cannot understand my purpose.", author = "Alduin" },
  { quote = "Your strength means nothing against my power.", author = "Alduin" },
  { quote = "I will consume the world until nothing remains.", author = "Alduin" },
  { quote = "You will bow before me or die.", author = "Alduin" },
  { quote = "All shall be consumed by fire.", author = "Alduin" },
  { quote = "I am the end of all things.", author = "Alduin" },
  { quote = "Your resistance is futile.", author = "Alduin" },
  { quote = "I am the harbinger of doom.", author = "Alduin" },
  { quote = "The cycle of life and death is mine to command.", author = "Alduin" },
  { quote = "You cannot escape your fate, Dragonborn.", author = "Alduin" },
  { quote = "Your actions are insignificant in the grand design.", author = "Alduin" },
  { quote = "I will reign supreme over all of Tamriel.", author = "Alduin" },
  { quote = "I am the terror that stalks the night.", author = "Alduin" },

  -- Thalmor Justiciar
  { quote = "The Thalmor will not be questioned.", author = "Thalmor Justiciar" },
  { quote = "You are in the presence of authority.", author = "Thalmor Justiciar" },
  { quote = "Our will is absolute, and we will not tolerate dissent.", author = "Thalmor Justiciar" },
  { quote = "The Dominion will rise again!", author = "Thalmor Justiciar" },
  { quote = "You are a fool to oppose us.", author = "Thalmor Justiciar" },
  { quote = "The time of the Nords is over.", author = "Thalmor Justiciar" },
  { quote = "We bring order to this chaotic world.", author = "Thalmor Justiciar" },
  { quote = "Do not think you can defy the Aldmeri Dominion.", author = "Thalmor Justiciar" },
  { quote = "Your people will kneel before us or face the consequences.", author = "Thalmor Justiciar" },
  { quote = "You are merely a pawn in a much larger game.", author = "Thalmor Justiciar" },
  { quote = "We do not need your approval.", author = "Thalmor Justiciar" },
  { quote = "The Aldmeri Dominion is the future.", author = "Thalmor Justiciar" },
  { quote = "Your resistance is futile.", author = "Thalmor Justiciar" },
  { quote = "You will regret crossing us.", author = "Thalmor Justiciar" },
  { quote = "We are not here to negotiate; we are here to command.", author = "Thalmor Justiciar" },
  { quote = "The Thalmor will bring peace, whether you like it or not.", author = "Thalmor Justiciar" },
  { quote = "You cannot fathom the strength of our resolve.", author = "Thalmor Justiciar" },
  { quote = "The Aldmeri Dominion will not be challenged.", author = "Thalmor Justiciar" },
  { quote = "You are in over your head.", author = "Thalmor Justiciar" },
  { quote = "The Nords are a relic of the past.", author = "Thalmor Justiciar" },
  { quote = "The Thalmor's power knows no bounds.", author = "Thalmor Justiciar" },

  -- Miraak
  { quote = "You are a fool to challenge me, Dragonborn.", author = "Miraak" },
  { quote = "I have waited long for this moment.", author = "Miraak" },
  { quote = "Your power is nothing compared to mine!", author = "Miraak" },
  { quote = "I will consume the souls of all who oppose me.", author = "Miraak" },
  { quote = "I was the first Dragonborn, and I will be the last.", author = "Miraak" },
  { quote = "I can feel your weakness, Dragonborn.", author = "Miraak" },
  { quote = "You will serve me, or you will die.", author = "Miraak" },
  { quote = "You cannot comprehend the power I wield.", author = "Miraak" },
  { quote = "I am the master of my own destiny.", author = "Miraak" },
  { quote = "You are a mere puppet, dancing to my tune.", author = "Miraak" },
  { quote = "The true power of the Thu'um is mine to command.", author = "Miraak" },
  { quote = "I will take what is rightfully mine!", author = "Miraak" },
  { quote = "Bow before your master!", author = "Miraak" },
  { quote = "I am not just a Dragonborn; I am a god!", author = "Miraak" },
  { quote = "Your fate is sealed, Dragonborn.", author = "Miraak" },
  { quote = "You will learn the hard way not to defy me.", author = "Miraak" },
  { quote = "I will show you the true meaning of power.", author = "Miraak" },
  { quote = "You are not worthy to stand against me.", author = "Miraak" },
  { quote = "Your arrogance will be your downfall.", author = "Miraak" },
  { quote = "I will crush you beneath my heel.", author = "Miraak" },

  -- M'aiq the Liar
  { quote = "M'aiq knows many things.", author = "M'aiq the Liar" },
  { quote = "M'aiq is not a hero.", author = "M'aiq the Liar" },
  { quote = "M'aiq is no one, and everyone.", author = "M'aiq the Liar" },
  { quote = "Sometimes, M'aiq tells the truth.", author = "M'aiq the Liar" },
  { quote = "M'aiq does not get involved in your affairs.", author = "M'aiq the Liar" },
  { quote = "M'aiq has seen many things.", author = "M'aiq the Liar" },
  { quote = "All of these things are true.", author = "M'aiq the Liar" },
  { quote = "If M'aiq had a tail, he would be happy.", author = "M'aiq the Liar" },
  { quote = "Life is but a dream, and M'aiq is dreaming.", author = "M'aiq the Liar" },
  { quote = "M'aiq loves to tell stories.", author = "M'aiq the Liar" },
  { quote = "M'aiq prefers to keep his secrets.", author = "M'aiq the Liar" },
  { quote = "M'aiq knows things you do not.", author = "M'aiq the Liar" },
  { quote = "You cannot catch M'aiq.", author = "M'aiq the Liar" },
  { quote = "M'aiq does not enjoy talking about himself.", author = "M'aiq the Liar" },
  { quote = "M'aiq does not like to be questioned.", author = "M'aiq the Liar" },
  { quote = "There are those who believe M'aiq is a myth.", author = "M'aiq the Liar" },
  { quote = "M'aiq enjoys the company of travelers.", author = "M'aiq the Liar" },
  { quote = "M'aiq often finds himself in peculiar situations.", author = "M'aiq the Liar" },
  { quote = "M'aiq is here to tell you stories.", author = "M'aiq the Liar" },
  { quote = "M'aiq knows what you seek.", author = "M'aiq the Liar" },
  { quote = "Do not question M'aiq's wisdom.", author = "M'aiq the Liar" },

  -- Brynjolf
  { quote = "I’ve been watching you.", author = "Brynjolf" },
  { quote = "Welcome to the Thieves Guild.", author = "Brynjolf" },
  { quote = "We’re all thieves here.", author = "Brynjolf" },
  { quote = "You’re not the first to get caught; you won’t be the last.", author = "Brynjolf" },
  { quote = "Keep your eyes open and your mouth shut.", author = "Brynjolf" },
  { quote = "There’s more to life than just making a living.", author = "Brynjolf" },
  { quote = "I’ll teach you how to be a better thief.", author = "Brynjolf" },
  { quote = "We have a saying in the Guild: 'Trust is a double-edged sword.'", author = "Brynjolf" },
  { quote = "You’re in good hands with the Guild.", author = "Brynjolf" },
  { quote = "Everyone has their secrets; it’s time you learn to keep yours.", author = "Brynjolf" },
  { quote = "The Guild's strength lies in our unity.", author = "Brynjolf" },
  { quote = "We’re all on the same side, for now.", author = "Brynjolf" },
  { quote = "I’ve made a few enemies in my time, but I always come out on top.", author = "Brynjolf" },
  { quote = "A good thief knows how to blend in.", author = "Brynjolf" },
  { quote = "It’s not about being the best; it’s about surviving.", author = "Brynjolf" },
  { quote = "The Guild doesn’t just steal; we make our mark.", author = "Brynjolf" },
  { quote = "Always have a plan, and always expect the unexpected.", author = "Brynjolf" },
  { quote = "A thief’s best asset is their wits.", author = "Brynjolf" },
  { quote = "There’s always a way to get what you want, if you’re clever enough.", author = "Brynjolf" },
  { quote = "You’re going to need a lot more than luck to survive in this city.", author = "Brynjolf" },
  { quote = "If you’re willing to put in the effort, the Guild can offer you a lot.", author = "Brynjolf" },

  -- Vex
  { quote = "I’m not just a thief; I’m an artist.", author = "Vex" },
  { quote = "I don’t need your help.", author = "Vex" },
  { quote = "You want something? Earn it.", author = "Vex" },
  { quote = "I run this Guild, and I make the rules.", author = "Vex" },
  { quote = "If you want to join, you have to prove yourself.", author = "Vex" },
  { quote = "The Guild is all that matters.", author = "Vex" },
  { quote = "You think you can intimidate me? Think again.", author = "Vex" },
  { quote = "I’ve seen a lot in my time; don’t test me.", author = "Vex" },
  { quote = "Every job has its risks.", author = "Vex" },
  { quote = "You’re not the first to try and rob me.", author = "Vex" },
  { quote = "I’ve always been good at getting what I want.", author = "Vex" },
  { quote = "The Thieves Guild will always endure, with or without you.", author = "Vex" },
  { quote = "You’ll learn respect in this Guild, one way or another.", author = "Vex" },
  { quote = "Loyalty has its rewards; betrayal has its consequences.", author = "Vex" },
  { quote = "Trust is earned, not given.", author = "Vex" },
  { quote = "You’re part of the Guild now; don’t screw it up.", author = "Vex" },
  { quote = "I don’t trust easily, and neither should you.", author = "Vex" },
  { quote = "You’ve got potential; I can see it.", author = "Vex" },
  { quote = "You think being a thief is easy? It’s a skill, a craft.", author = "Vex" },
  { quote = "If you can’t steal, you can’t survive in this city.", author = "Vex" },
  { quote = "Always keep your eyes on the prize; distractions will get you caught.", author = "Vex" },

  -- Nocturnal
  { quote = "I am the Night Mother; I am the darkness that swallows the light.", author = "Nocturnal" },
  { quote = "You’re not worthy of my blessings.", author = "Nocturnal" },
  { quote = "Your path is chosen; now you must follow it.", author = "Nocturnal" },
  { quote = "The shadows are your ally; embrace them.", author = "Nocturnal" },
  { quote = "You are a Nightingale; your skills are unmatched.", author = "Nocturnal" },
  { quote = "Your fate is intertwined with the shadows.", author = "Nocturnal" },
  { quote = "Walk the path of darkness, and I will guide you.", author = "Nocturnal" },
  { quote = "I grant you power, but it comes with a price.", author = "Nocturnal" },
  { quote = "Trust the shadows; they will protect you.", author = "Nocturnal" },
  { quote = "You serve the darkness; it serves you in return.", author = "Nocturnal" },
  { quote = "The night is my domain; fear it not.", author = "Nocturnal" },
  { quote = "Only the worthy shall walk among the shadows.", author = "Nocturnal" },
  { quote = "In darkness, you will find the truth.", author = "Nocturnal" },
  { quote = "You have chosen wisely; the shadows will embrace you.", author = "Nocturnal" },
  { quote = "Remember, the night can be your greatest ally.", author = "Nocturnal" },
  { quote = "Your journey is just beginning; trust in the darkness.", author = "Nocturnal" },
  { quote = "The darkness is not to be feared, but to be embraced.", author = "Nocturnal" },
  { quote = "Let your heart be your compass in the dark.", author = "Nocturnal" },
  { quote = "The shadows whisper; listen closely.", author = "Nocturnal" },
  { quote = "In the end, we are all bound by the shadows.", author = "Nocturnal" },

  -- Karliah
  { quote = "I was always meant to be a Nightingale.", author = "Karliah" },
  { quote = "The Guild is my family, and I will do anything to protect it.", author = "Karliah" },
  { quote = "You think you know betrayal? You have no idea.", author = "Karliah" },
  { quote = "The past is just that: the past. Focus on the future.", author = "Karliah" },
  { quote = "I will reveal the truth, no matter the cost.", author = "Karliah" },
  { quote = "The Guild's strength lies in its unity.", author = "Karliah" },
  { quote = "Not all who wander are lost; some are just searching for answers.", author = "Karliah" },
  { quote = "Trust is a rare commodity in our line of work.", author = "Karliah" },
  { quote = "I won’t let you down; the Guild needs us both.", author = "Karliah" },
  { quote = "You have the heart of a thief; embrace it.", author = "Karliah" },
  { quote = "There's no honor among thieves; only trust.", author = "Karliah" },
  { quote = "My past doesn't define me; my choices do.", author = "Karliah" },
  { quote = "Even the darkest paths can lead to light.", author = "Karliah" },
  { quote = "Sometimes, we must act in the shadows to protect what we love.", author = "Karliah" },
  { quote = "A true thief knows when to strike and when to retreat.", author = "Karliah" },
  { quote = "Loyalty is the greatest gift you can give.", author = "Karliah" },
  { quote = "In darkness, we find our strength.", author = "Karliah" },
  { quote = "Every choice has its consequences; choose wisely.", author = "Karliah" },
  { quote = "You can't steal a heart without first knowing its worth.", author = "Karliah" },
  { quote = "The past is behind us; what matters is the future we forge.", author = "Karliah" },

  -- Gallus Desidenius
  { quote = "I was the best thief the Guild ever had.", author = "Gallus Desidenius" },
  { quote = "The Guild will rise from its ashes, I promise you.", author = "Gallus Desidenius" },
  { quote = "The shadows were my home; I never feared them.", author = "Gallus Desidenius" },
  { quote = "In the end, it all comes down to trust.", author = "Gallus Desidenius" },
  { quote = "You think you can outsmart me? Think again.", author = "Gallus Desidenius" },
  { quote = "The Guild has been betrayed, but it can still thrive.", author = "Gallus Desidenius" },
  { quote = "I knew the risks, and I accepted them.", author = "Gallus Desidenius" },
  { quote = "You don’t get to where I am without making sacrifices.", author = "Gallus Desidenius" },
  { quote = "A thief’s greatest weapon is their mind.", author = "Gallus Desidenius" },
  { quote = "The night holds many secrets; embrace them.", author = "Gallus Desidenius" },
  { quote = "To be a Nightingale is to be part of something greater.", author = "Gallus Desidenius" },
  { quote = "We walk in darkness, but our hearts shine bright.", author = "Gallus Desidenius" },
  { quote = "Power comes from knowledge; seek it out.", author = "Gallus Desidenius" },
  { quote = "You must be cunning to survive in this world.", author = "Gallus Desidenius" },
  { quote = "Every thief has a story; make yours legendary.", author = "Gallus Desidenius" },
  { quote = "In the shadows, we find our true selves.", author = "Gallus Desidenius" },
  { quote = "Let the Guild be your guiding light.", author = "Gallus Desidenius" },
  { quote = "Without risk, there is no reward.", author = "Gallus Desidenius" },
  { quote = "You can’t change the past, but you can shape the future.", author = "Gallus Desidenius" },
  { quote = "The best heist is one where no one even knows they were robbed.", author = "Gallus Desidenius" },
  { quote = "A true thief thrives in chaos.", author = "Gallus Desidenius" },

  -- Maven Black-Briar
  { quote = "I don't care what you think you know. The Guild will rise again.", author = "Maven Black-Briar" },
  { quote = "A clever thief knows when to make an exit.", author = "Maven Black-Briar" },
  { quote = "You’re not the only one who’s made mistakes in life.", author = "Maven Black-Briar" },
  { quote = "The Black-Briar family has a long history of power.", author = "Maven Black-Briar" },
  { quote = "Remember, business is business. Don’t take it personally.", author = "Maven Black-Briar" },
  { quote = "Everyone has a price; you just need to find it.", author = "Maven Black-Briar" },
  { quote = "Don’t underestimate the importance of a good reputation.", author = "Maven Black-Briar" },
  { quote = "You can’t buy loyalty; it has to be earned.", author = "Maven Black-Briar" },
  { quote = "I run this city, and I will not be disrespected.", author = "Maven Black-Briar" },
  { quote = "The Guild may be weak now, but it won't stay that way for long.", author = "Maven Black-Briar" },
  { quote = "You’re either with me or against me. Choose wisely.", author = "Maven Black-Briar" },
  { quote = "I won’t tolerate failure. Not now, not ever.", author = "Maven Black-Briar" },
  {
    quote = "You’re not the first to try and take me down, and you won’t be the last.",
    author = "Maven Black-Briar",
  },
  { quote = "Power is everything. You either have it or you don’t.", author = "Maven Black-Briar" },
  { quote = "Make your choices carefully; I don’t give second chances.", author = "Maven Black-Briar" },
  { quote = "The Guild is more than just a group of thieves; it's a family.", author = "Maven Black-Briar" },
  { quote = "You need to learn to keep your mouth shut.", author = "Maven Black-Briar" },
  { quote = "Don't expect any mercy from me.", author = "Maven Black-Briar" },
  { quote = "You have no idea what I’m capable of.", author = "Maven Black-Briar" },
  { quote = "The city’s secrets are mine to keep.", author = "Maven Black-Briar" },

  -- The Ancient Falmer
  { quote = "The sun was once our ally; now it is our enemy.", author = "The Ancient Falmer" },
  { quote = "We were betrayed by those who sought power.", author = "The Ancient Falmer" },
  { quote = "Our songs are lost to the winds of time.", author = "The Ancient Falmer" },
  { quote = "Once, we thrived beneath the sunlit skies.", author = "The Ancient Falmer" },
  { quote = "We walked in the light of the gods, but now we dwell in darkness.", author = "The Ancient Falmer" },
  { quote = "The depths of our sorrow run deeper than any chasm.", author = "The Ancient Falmer" },
  { quote = "Our legacy is buried in the ruins of our past.", author = "The Ancient Falmer" },
  { quote = "We were once the masters of the night.", author = "The Ancient Falmer" },
  { quote = "Betrayed by our kin, we are lost to history.", author = "The Ancient Falmer" },
  { quote = "In our quest for knowledge, we sealed our own fate.", author = "The Ancient Falmer" },
  { quote = "The frost of the mountain is our only companion now.", author = "The Ancient Falmer" },
  { quote = "Once, we were a proud race; now we are shadows of our former selves.", author = "The Ancient Falmer" },
  { quote = "We were the children of the sky, but the ground has claimed us.", author = "The Ancient Falmer" },
  { quote = "The whispers of the past echo in our hearts.", author = "The Ancient Falmer" },
  { quote = "In darkness, we have found our true nature.", author = "The Ancient Falmer" },
  { quote = "The light fades; all we have left is the dark.", author = "The Ancient Falmer" },
  { quote = "Every shadow tells a tale of our lost glory.", author = "The Ancient Falmer" },
  { quote = "We have become what we once feared the most.", author = "The Ancient Falmer" },
  { quote = "The roots of our pain run deep; they cannot be severed.", author = "The Ancient Falmer" },
  { quote = "We sought to understand the mysteries of the world, but it consumed us.", author = "The Ancient Falmer" },
  { quote = "Even now, we remember the taste of sunlight.", author = "The Ancient Falmer" },

  -- Ralof
  { quote = "Hey, you. You're finally awake.", author = "Ralof" },
  { quote = "You were trying to cross the border, right?", author = "Ralof" },
  { quote = "We’re all brothers and sisters in binds now, thief.", author = "Ralof" },
  { quote = "Skyrim was fine until you came along. Empire was nice and lazy.", author = "Ralof" },
  {
    quote = "I used to be sweet on a girl from here. Wonder if Vilod is still making that mead with juniper berries mixed in.",
    author = "Ralof",
  },
  { quote = "I bet they had something to do with this.", author = "Ralof" },
  { quote = "Ulfric? The Jarl of Windhelm?", author = "Ralof" },
  { quote = "The true High King.", author = "Ralof" },
  { quote = "Oh gods, where are they taking us?", author = "Ralof" },
  { quote = "This isn't happening. This isn't happening!", author = "Ralof" },
  {
    quote = "General Tullius, the military governor. And it looks like the Thalmor are with him. Damn elves. I bet they had something to do with this.",
    author = "Ralof",
  },
  { quote = "Look at him. General Tullius the butcher.", author = "Ralof" },
  { quote = "There’s a bear just ahead. See her? I’d rather not tangle with her right now.", author = "Ralof" },
  { quote = "Talos preserve us.", author = "Ralof" },
  { quote = "It's the Imperials. They ambushed us outside Darkwater Crossing.", author = "Ralof" },
  { quote = "We should keep moving. Come here. Let me see if I can get those bindings off.", author = "Ralof" },
  { quote = "Damn, that dragon doesn't give up easy.", author = "Ralof" },
  { quote = "Looks like we're the only ones who made it.", author = "Ralof" },
  { quote = "By Ysmir, you've come. You've truly come!", author = "Ralof" },
  { quote = "It's Ulfric Stormcloak himself!", author = "Ralof" },
}
