return {
  {
    quote = "What is better - to be born good, or to overcome your evil nature through great effort?",
    author = "Paarthurnax",
  },
  { quote = "Dovahkiin. You have tasted the Voice of the Graybeards and passed through.", author = "Paarthurnax" },
  {
    quote = "Power. You have it, as do all dov. But power is inert without action and choice.",
    author = "Paarthurnax",
  },
  { quote = "The past is unchangeable, but you have the power to shape the future.", author = "Paarthurnax" },
  { quote = "There is a difference between knowing a path and walking it.", author = "Paarthurnax" },
  { quote = "You must understand the truth of your own nature, Dovahkiin.", author = "Paarthurnax" },
  { quote = "Alduin's hunger will consume all, but you have the strength to resist.", author = "Paarthurnax" },
  { quote = "Is it not enough that I have lived for thousands of years, trying to atone?", author = "Paarthurnax" },
  { quote = "To be a true Dovahkiin, you must embrace your destiny.", author = "Paarthurnax" },
  { quote = "A shout can alter the course of fate, but it must be wielded wisely.", author = "Paarthurnax" },
  { quote = "The way of the Voice is a path filled with trials and tribulations.", author = "Paarthurnax" },
  { quote = "Each dragon born possesses a unique power and destiny.", author = "Paarthurnax" },
  { quote = "Courage is not the absence of fear, but the triumph over it.", author = "Paarthurnax" },
  { quote = "A dragon's strength lies not just in its power, but in its wisdom.", author = "Paarthurnax" },
  { quote = "You must learn to listen to the voices of your ancestors.", author = "Paarthurnax" },
  { quote = "Not all dragons are foes; some can be allies.", author = "Paarthurnax" },
  { quote = "Understanding is the key to unlocking true power.", author = "Paarthurnax" },
  { quote = "Your past does not define you; your choices do.", author = "Paarthurnax" },
  { quote = "Fear is a powerful motivator, but it can also be a great enemy.", author = "Paarthurnax" },
  { quote = "Through understanding, you can forge your own path.", author = "Paarthurnax" },
  { quote = "Your voice holds power; use it to bring about change.", author = "Paarthurnax" },
  { quote = "Strength without wisdom is a dangerous weapon.", author = "Paarthurnax" },
  { quote = "To know your enemy is to know yourself.", author = "Paarthurnax" },
  { quote = "The path of knowledge is a never-ending journey.", author = "Paarthurnax" },
  { quote = "In the face of adversity, true character is revealed.", author = "Paarthurnax" },
  { quote = "Even in darkness, there is a flicker of light.", author = "Paarthurnax" },
  { quote = "The future is shaped by the choices you make today.", author = "Paarthurnax" },
  { quote = "Your heart is your greatest ally, listen to its guidance.", author = "Paarthurnax" },
  { quote = "Every action has consequences, be mindful of them.", author = "Paarthurnax" },
  { quote = "Every great journey begins with a single step.", author = "Paarthurnax" },
  { quote = "Embrace your destiny, for it is yours alone to fulfill.", author = "Paarthurnax" },
  { quote = "The bond between allies can withstand the harshest trials.", author = "Paarthurnax" },
  { quote = "Even the most powerful among us are bound by their choices.", author = "Paarthurnax" },
  { quote = "True freedom comes from within.", author = "Paarthurnax" },
  { quote = "Let your heart guide you; it knows the way.", author = "Paarthurnax" },
  { quote = "A wise person learns more from their enemies than from their friends.", author = "Paarthurnax" },
  { quote = "A smile can hide the deepest sorrow.", author = "Paarthurnax" },
  { quote = "The past may haunt you, but it does not have to define you.", author = "Paarthurnax" },
  { quote = "Through adversity, we find our strength.", author = "Paarthurnax" },
  { quote = "Every encounter is a lesson; every lesson an opportunity for growth.", author = "Paarthurnax" },
  { quote = "Your choices shape your destiny; choose wisely.", author = "Paarthurnax" },
  { quote = "Embrace change; it is the only constant.", author = "Paarthurnax" },
  { quote = "The journey of a thousand miles begins with a single step.", author = "Paarthurnax" },
  { quote = "In the face of adversity, true strength is revealed.", author = "Paarthurnax" },
  { quote = "The pursuit of knowledge is a noble quest.", author = "Paarthurnax" },
  { quote = "Hope is the light that guides us through the darkest times.", author = "Paarthurnax" },
  { quote = "Forgiveness is a powerful weapon; wield it wisely.", author = "Paarthurnax" },
  { quote = "The greatest battles are fought within.", author = "Paarthurnax" },
  { quote = "Every end is a new beginning; embrace the change.", author = "Paarthurnax" },
  { quote = "Let your choices reflect your true self.", author = "Paarthurnax" },
  { quote = "Courage is the key to unlocking your potential.", author = "Paarthurnax" },
  { quote = "Your heart knows the way; trust it.", author = "Paarthurnax" },
  { quote = "The world is filled with wonders; take time to explore.", author = "Paarthurnax" },
  { quote = "Love is a strength that binds us together.", author = "Paarthurnax" },
  { quote = "Time is a river; we are but leaves upon its surface.", author = "Paarthurnax" },
  { quote = "In the stillness of the night, wisdom speaks the loudest.", author = "Paarthurnax" },
  { quote = "True peace comes from within; cultivate it daily.", author = "Paarthurnax" },
  { quote = "Life is a tapestry woven with the threads of our choices.", author = "Paarthurnax" },
  { quote = "Your story is yours to write; pen it with intention.", author = "Paarthurnax" },
  { quote = "The path to greatness is paved with perseverance.", author = "Paarthurnax" },
  { quote = "Strength lies not in power, but in compassion.", author = "Paarthurnax" },
  { quote = "A true friend stands by your side, even in darkness.", author = "Paarthurnax" },
  { quote = "The whispers of the past guide us towards the future.", author = "Paarthurnax" },
  { quote = "In every challenge lies an opportunity for growth.", author = "Paarthurnax" },
  { quote = "The dance of life is a symphony of choices and consequences.", author = "Paarthurnax" },
  { quote = "A heart full of gratitude can weather any storm.", author = "Paarthurnax" },
  { quote = "The journey of self-discovery is the most important quest of all.", author = "Paarthurnax" },
  { quote = "The world is full of mysteries. Seek them out.", author = "Paarthurnax" },
  { quote = "Every warrior has a story. What is yours?", author = "Ulfric Stormcloak" },
  { quote = "Courage is not the absence of fear, but the triumph over it.", author = "Aela the Huntress" },
  { quote = "When the dragon flies, the world trembles.", author = "Delphine" },
  { quote = "Your choices shape your destiny. Choose wisely.", author = "Esbern" },
  { quote = "We cannot change the past, but we can learn from it.", author = "Farengar Secret-Fire" },
  { quote = "The path to power is often paved with sacrifice.", author = "Maven Black-Briar" },
  { quote = "What is done cannot be undone. But we can make amends.", author = "Cicero" },
  { quote = "Every life has its trials. Endure and you will prevail.", author = "Astrid" },
  { quote = "The thrill of the hunt is what keeps me alive.", author = "Aela the Huntress" },
  { quote = "Hope is the beacon that guides us through darkness.", author = "Delphine" },
  { quote = "Never forget the sacrifices of those who came before you.", author = "Ulfric Stormcloak" },
  { quote = "Strength comes from unity; together we are invincible.", author = "Maven Black-Briar" },
  { quote = "The winds of change are upon us; embrace them.", author = "Esbern" },
  { quote = "A dragon's roar can shake the heavens, but so can your voice.", author = "Paarthurnax" },
  { quote = "In the heart of every warrior lies the spirit of a dragon.", author = "Ulfric Stormcloak" },
  { quote = "The echoes of our ancestors guide us forward.", author = "Esbern" },
  { quote = "Our choices echo through time. Choose wisely.", author = "Paarthurnax" },
  { quote = "In the depths of despair, hope is a fragile light.", author = "Maven Black-Briar" },
  { quote = "The bonds of friendship can withstand the fiercest storms.", author = "Aela the Huntress" },
  { quote = "You hold the power to shape your own destiny.", author = "Delphine" },
  { quote = "Let your heart lead the way; it knows the truth.", author = "Ulfric Stormcloak" },
  { quote = "The road to greatness is paved with trials and challenges.", author = "Esbern" },
}
