local function get_random_header_quote()
  local header_quotes = {
    {
      quote = "What is better - to be born good, or to overcome your evil nature through great effort?",
      author = "Paarthurnax",
    },
    { quote = "Dovahkiin. You have tasted the Voice of the Graybeards and passed through.", author = "Paarthurnax" },
    {
      quote = "Power. You have it, as do all dov. But power is inert without action and choice.",
      author = "Paarthurnax",
    },
    { quote = "The past is unchangeable, but you have the power to shape the future.", author = "Paarthurnax" },
    { quote = "There is a difference between knowing a path and walking it.", author = "Paarthurnax" },
    { quote = "You must understand the truth of your own nature, Dovahkiin.", author = "Paarthurnax" },
    { quote = "Alduin's hunger will consume all, but you have the strength to resist.", author = "Paarthurnax" },
    { quote = "Is it not enough that I have lived for thousands of years, trying to atone?", author = "Paarthurnax" },
    { quote = "To be a true Dovahkiin, you must embrace your destiny.", author = "Paarthurnax" },
    { quote = "A shout can alter the course of fate, but it must be wielded wisely.", author = "Paarthurnax" },
    { quote = "The way of the Voice is a path filled with trials and tribulations.", author = "Paarthurnax" },
    { quote = "Each dragon born possesses a unique power and destiny.", author = "Paarthurnax" },
    { quote = "Courage is not the absence of fear, but the triumph over it.", author = "Paarthurnax" },
    { quote = "A dragon's strength lies not just in its power, but in its wisdom.", author = "Paarthurnax" },
    { quote = "You must learn to listen to the voices of your ancestors.", author = "Paarthurnax" },
    { quote = "Not all dragons are foes; some can be allies.", author = "Paarthurnax" },
    { quote = "Understanding is the key to unlocking true power.", author = "Paarthurnax" },
    { quote = "Your past does not define you; your choices do.", author = "Paarthurnax" },
    { quote = "Fear is a powerful motivator, but it can also be a great enemy.", author = "Paarthurnax" },
    { quote = "Through understanding, you can forge your own path.", author = "Paarthurnax" },
    { quote = "Your voice holds power; use it to bring about change.", author = "Paarthurnax" },
    { quote = "Strength without wisdom is a dangerous weapon.", author = "Paarthurnax" },
    { quote = "To know your enemy is to know yourself.", author = "Paarthurnax" },
    { quote = "The path of knowledge is a never-ending journey.", author = "Paarthurnax" },
    { quote = "In the face of adversity, true character is revealed.", author = "Paarthurnax" },
    { quote = "Even in darkness, there is a flicker of light.", author = "Paarthurnax" },
    { quote = "The future is shaped by the choices you make today.", author = "Paarthurnax" },
    { quote = "Your heart is your greatest ally, listen to its guidance.", author = "Paarthurnax" },
    { quote = "Every action has consequences, be mindful of them.", author = "Paarthurnax" },
    { quote = "Every great journey begins with a single step.", author = "Paarthurnax" },
    { quote = "Embrace your destiny, for it is yours alone to fulfill.", author = "Paarthurnax" },
    { quote = "The bond between allies can withstand the harshest trials.", author = "Paarthurnax" },
    { quote = "Even the most powerful among us are bound by their choices.", author = "Paarthurnax" },
    { quote = "True freedom comes from within.", author = "Paarthurnax" },
    { quote = "Let your heart guide you; it knows the way.", author = "Paarthurnax" },
    { quote = "A wise person learns more from their enemies than from their friends.", author = "Paarthurnax" },
    { quote = "A smile can hide the deepest sorrow.", author = "Paarthurnax" },
    { quote = "The past may haunt you, but it does not have to define you.", author = "Paarthurnax" },
    { quote = "Through adversity, we find our strength.", author = "Paarthurnax" },
    { quote = "Every encounter is a lesson; every lesson an opportunity for growth.", author = "Paarthurnax" },
    { quote = "Your choices shape your destiny; choose wisely.", author = "Paarthurnax" },
    { quote = "Embrace change; it is the only constant.", author = "Paarthurnax" },
    { quote = "The journey of a thousand miles begins with a single step.", author = "Paarthurnax" },
    { quote = "In the face of adversity, true strength is revealed.", author = "Paarthurnax" },
    { quote = "The pursuit of knowledge is a noble quest.", author = "Paarthurnax" },
    { quote = "Hope is the light that guides us through the darkest times.", author = "Paarthurnax" },
    { quote = "Forgiveness is a powerful weapon; wield it wisely.", author = "Paarthurnax" },
    { quote = "The greatest battles are fought within.", author = "Paarthurnax" },
    { quote = "Every end is a new beginning; embrace the change.", author = "Paarthurnax" },
    { quote = "Let your choices reflect your true self.", author = "Paarthurnax" },
    { quote = "Courage is the key to unlocking your potential.", author = "Paarthurnax" },
    { quote = "Your heart knows the way; trust it.", author = "Paarthurnax" },
    { quote = "The world is filled with wonders; take time to explore.", author = "Paarthurnax" },
    { quote = "Love is a strength that binds us together.", author = "Paarthurnax" },
    { quote = "Time is a river; we are but leaves upon its surface.", author = "Paarthurnax" },
    { quote = "In the stillness of the night, wisdom speaks the loudest.", author = "Paarthurnax" },
    { quote = "True peace comes from within; cultivate it daily.", author = "Paarthurnax" },
    { quote = "Life is a tapestry woven with the threads of our choices.", author = "Paarthurnax" },
    { quote = "Your story is yours to write; pen it with intention.", author = "Paarthurnax" },
    { quote = "The path to greatness is paved with perseverance.", author = "Paarthurnax" },
    { quote = "Strength lies not in power, but in compassion.", author = "Paarthurnax" },
    { quote = "A true friend stands by your side, even in darkness.", author = "Paarthurnax" },
    { quote = "The whispers of the past guide us towards the future.", author = "Paarthurnax" },
    { quote = "In every challenge lies an opportunity for growth.", author = "Paarthurnax" },
    { quote = "The dance of life is a symphony of choices and consequences.", author = "Paarthurnax" },
    { quote = "A heart full of gratitude can weather any storm.", author = "Paarthurnax" },
    { quote = "The journey of self-discovery is the most important quest of all.", author = "Paarthurnax" },
    { quote = "The world is full of mysteries. Seek them out.", author = "Paarthurnax" },
    { quote = "Every warrior has a story. What is yours?", author = "Ulfric Stormcloak" },
    { quote = "Courage is not the absence of fear, but the triumph over it.", author = "Aela the Huntress" },
    { quote = "When the dragon flies, the world trembles.", author = "Delphine" },
    { quote = "Your choices shape your destiny. Choose wisely.", author = "Esbern" },
    { quote = "We cannot change the past, but we can learn from it.", author = "Farengar Secret-Fire" },
    { quote = "The path to power is often paved with sacrifice.", author = "Maven Black-Briar" },
    { quote = "What is done cannot be undone. But we can make amends.", author = "Cicero" },
    { quote = "Every life has its trials. Endure and you will grow stronger.", author = "Balgruuf the Greater" },
    { quote = "In the end, we are all but dust in the wind.", author = "Alduin" },
    { quote = "Strength lies not in the blade, but in the heart.", author = "Aela the Huntress" },
    { quote = "A true hero protects those who cannot protect themselves.", author = "General Tullius" },
    { quote = "Do not seek revenge; seek justice.", author = "Astrid" },
    { quote = "The greatest power is often hidden in the smallest of things.", author = "Miraak" },
    { quote = "Trust is a weapon. Use it wisely.", author = "Thalmor Ambassador" },
    { quote = "Wisdom comes from experience. Learn from every encounter.", author = "Farengar Secret-Fire" },
    { quote = "Honor is worth more than gold.", author = "Ulfric Stormcloak" },
    { quote = "Sometimes, the strongest bonds are forged in the fires of adversity.", author = "Delphine" },
    { quote = "Only a fool underestimates their enemies.", author = "Maven Black-Briar" },
    { quote = "Our choices define who we are.", author = "Cicero" },
    { quote = "Even the smallest candle can light the darkest night.", author = "Esbern" },
    { quote = "The past is a guide, not a prison.", author = "Alduin" },
    { quote = "To face the unknown is to embrace true courage.", author = "Balgruuf the Greater" },
    { quote = "A wise leader knows when to listen.", author = "General Tullius" },
    { quote = "Fear can be a great teacher if you let it.", author = "Aela the Huntress" },
    { quote = "Every battle won brings us closer to peace.", author = "Ulfric Stormcloak" },
    { quote = "Your heart is your greatest weapon.", author = "Paarthurnax" },
    { quote = "Strength comes from within.", author = "Miraak" },
    { quote = "A true warrior fights not for glory, but for honor.", author = "Delphine" },
    { quote = "Time is the fire in which we burn.", author = "Farengar Secret-Fire" },
    { quote = "Sometimes, to achieve peace, one must fight.", author = "Astrid" },
    { quote = "The bonds we form in battle are unbreakable.", author = "Aela the Huntress" },
    { quote = "Every day is a chance to write your own story.", author = "Maven Black-Briar" },
    { quote = "You cannot outrun your destiny.", author = "General Tullius" },
    { quote = "Cunning can outsmart strength.", author = "Cicero" },
    { quote = "The mightiest dragon can fall to the simplest of arrows.", author = "Alduin" },
    { quote = "Forgiveness is a strength few possess.", author = "Esbern" },
    { quote = "Even the toughest armor has its weaknesses.", author = "Balgruuf the Greater" },
    { quote = "In every heart lies the potential for greatness.", author = "Paarthurnax" },
    { quote = "Victory is earned through sacrifice.", author = "Ulfric Stormcloak" },
    { quote = "Your mind is your greatest ally.", author = "Miraak" },
    { quote = "History is written by those who dare to act.", author = "General Tullius" },
    { quote = "Courage is not a destination, but a journey.", author = "Aela the Huntress" },
    { quote = "Truth is a double-edged sword; wield it carefully.", author = "Maven Black-Briar" },
    { quote = "Each moment is a chance to change your fate.", author = "Cicero" },
    { quote = "In the darkness, even the smallest light shines bright.", author = "Esbern" },
    { quote = "The past may haunt us, but it does not define us.", author = "Alduin" },
    { quote = "Every warrior must choose their path.", author = "Balgruuf the Greater" },
    { quote = "A wise choice can alter the course of destiny.", author = "Farengar Secret-Fire" },
    { quote = "Fear can be a friend or foe; it's up to you.", author = "Astrid" },
    { quote = "The way is dangerous, but the reward is worth it.", author = "Delphine" },
    { quote = "Nothing is more important than loyalty.", author = "Ulfric Stormcloak" },
    { quote = "The winds of change are blowing through Skyrim.", author = "Paarthurnax" },
    { quote = "Sometimes, the smallest of actions can lead to the greatest of consequences.", author = "Astrid" },
    { quote = "Fear is the mind killer; embrace the strength of your spirit.", author = "Farengar Secret-Fire" },
    { quote = "The only true wisdom is in knowing you know nothing.", author = "The Graybeards" },
    { quote = "Beneath the layers of ice, the heart of Skyrim beats strong.", author = "Aela the Huntress" },
    { quote = "The dragons are not mere beasts; they are part of our history.", author = "Paarthurnax" },
    { quote = "We are all bound by the chains of our past.", author = "Esbern" },
    { quote = "True strength comes from understanding and accepting your limits.", author = "Balgruuf the Greater" },
    { quote = "Every action leaves a mark on the world.", author = "Lydia" },
    { quote = "In darkness, there is always a glimmer of light.", author = "Serana" },
    { quote = "A hunter must be as silent as the night.", author = "Aela the Huntress" },
    { quote = "Let the past guide you, but do not be bound by it.", author = "Tullius" },
    { quote = "The life of a warrior is a life of hardship and sacrifice.", author = "Farkas" },
    { quote = "To seek power without understanding is to invite destruction.", author = "Paarthurnax" },
    { quote = "The weight of your choices shapes the path ahead.", author = "Brynjolf" },
    { quote = "Every blade has a story; make yours worth telling.", author = "Mjoll the Lioness" },
    { quote = "Trust is a rare gift in these troubled times.", author = "Elenwen" },
    { quote = "The dragons may be our enemies, but they are also our teachers.", author = "Paarthurnax" },
    { quote = "True beauty lies in the strength of one's character.", author = "Mjoll the Lioness" },
    { quote = "War is not just a matter of weapons; it is a battle of hearts.", author = "Ulfric Stormcloak" },
    { quote = "In every corner of Skyrim, stories wait to be told.", author = "Aerin" },
    { quote = "Every shadow hides a story, waiting to be revealed.", author = "Astrid" },
    { quote = "A true leader is measured by their compassion and courage.", author = "Balgruuf the Greater" },
    { quote = "The past is but a shadow; the future is ours to shape.", author = "Paarthurnax" },
    { quote = "Wisdom is knowing when to act and when to hold back.", author = "Paarthurnax" },
    { quote = "In every heart lies the potential for greatness.", author = "Aela the Huntress" },
    { quote = "The mind is as sharp as the sword; both must be honed.", author = "Farengar Secret-Fire" },
    { quote = "What lies beneath the surface is often the most profound.", author = "Esbern" },
    { quote = "The fire of a dragon can cleanse or destroy; it is the wielder's choice.", author = "Paarthurnax" },
    { quote = "Every path has its challenges; face them with courage.", author = "Lydia" },
    { quote = "What is done cannot be undone, but it can be learned from.", author = "Delphine" },
    { quote = "To walk in another's shoes is to understand their journey.", author = "Serana" },
    { quote = "Strength is not just in muscles, but in resolve.", author = "Farkas" },
    { quote = "Only through challenge do we truly discover ourselves.", author = "Brynjolf" },
    { quote = "The bonds we forge can become our greatest weapons.", author = "Ulfric Stormcloak" },
    { quote = "In the face of adversity, the true self is revealed.", author = "Mjoll the Lioness" },
    { quote = "The winds of destiny can change in an instant.", author = "Paarthurnax" },
    { quote = "Courage is not the absence of fear, but the triumph over it.", author = "Urag gro-Shub" },
    { quote = "What we do in life echoes in eternity.", author = "Vignar Grey-Mane" },
    { quote = "The soul of Skyrim resides in its people.", author = "Ulfric Stormcloak" },
    { quote = "Trust must be earned, not freely given.", author = "Delphine" },
    { quote = "The time for action is now; hesitation only breeds regret.", author = "Bersi Honey-Hand" },
    { quote = "Adventure awaits those brave enough to seek it.", author = "Kjeld" },
    { quote = "A strong heart can overcome any obstacle.", author = "Aela the Huntress" },
    { quote = "The voice of the dragon can shake the very foundations of the world.", author = "Paarthurnax" },
    { quote = "In unity, there is strength.", author = "Ulfric Stormcloak" },
    { quote = "Wisdom is the light that guides the lost.", author = "Farengar Secret-Fire" },
    { quote = "A true warrior fights not for glory, but for honor.", author = "Balgruuf the Greater" },
    { quote = "The world is full of mysteries waiting to be uncovered.", author = "Esbern" },
  }
  local random_index = math.random(#header_quotes)
  local selected_quote = header_quotes[random_index]

  return selected_quote.quote .. "\n-" .. selected_quote.author
end

local function get_random_footer_quote()
  local footer_quotes = {
    { "The Thu'um, or Shout, is the ancient Nord art of using the voice to battle." },
    { "Nords are natural-born warriors. In battle, they fight with an extra fervor." },
    { "Mages that favor the school of Destruction use spells to deal elemental damage." },
    { "Standing stones grant special abilities. There are 13 standing stones in all." },
    { "The ancient Nords worshiped dragons as gods, and many ruins are remnants of." },
    { "Blacksmiths can forge weapons and armor from raw materials found in the world." },
    { "Dragonsreach, the palace of Whiterun's Jarl, was built to house a captured dragon." },
    { "Vampires are undead creatures that drain the life from their victims by biting." },
    { "The compulsion to collect and hoard treasure is known as 'avarice'." },
    { "No matter how powerful, a dragon's heart is not immune to a mortal's sword." },
    { "An arrow in the knee can end a warrior's journey and force him to rethink his path." },
    { "The Night Mother watches over her children, the Dark Brotherhood." },
    { "The Daedric Princes often meddle in the affairs of mortals." },
    { "Nordic tombs are filled with ancient treasures, but also with dangers." },
    { "Werewolves are cursed to transform during the full moon, seeking blood." },
    { "Skooma is a dangerous narcotic made from moon sugar." },
    { "Alchemy is the art of creating potions and poisons from various ingredients." },
    { "The Blades are an ancient order sworn to protect the Dragonborn." },
    { "The All-Maker is worshiped by the Skaal of Solstheim." },
    { "Dwarven ruins are filled with the mysteries of the long-lost Dwemer." },
    { "A good hunter knows how to track their prey and avoid danger." },
    { "Skyrim's climate is harsh, but the beauty of its landscape is undeniable." },
    { "The Thieves Guild operates in the shadows, ensuring their secrets remain hidden." },
    { "Elves and humans have a long and complicated history, filled with conflict." },
    { "Falmer, once the Snow Elves, now dwell in the dark places of the world." },
    { "The College of Winterhold is a haven for those who wish to study magic." },
    { "The Dragonborn can wield the power of the Thu'um to summon dragons." },
    { "Some believe the Hist are sentient trees that provide guidance to the Argonians." },
    { "The Sloads are a reclusive race, often shunned by other Tamrielic cultures." },
    { "Horkers are blubbery beasts often hunted for their meat and tusks." },
    { "A true hero knows when to act and when to observe." },
    { "A warm fire and good company can make even the longest nights bearable." },
    { "The White-Gold Concordat brought peace, but at a cost." },
    { "The Dragonborn's destiny is not set in stone; it is a path forged by choice." },
    { "The return of dragons has changed the balance of power in Skyrim." },
    { "Many adventurers seek fame, but few return to tell the tale." },
    { "The spirits of the dead linger in the halls of Sovngarde." },
    { "Each of the Nine Divines has their own domain and purpose." },
    { "A warrior's honor is their most valuable possession." },
    { "The land of Skyrim is filled with secrets waiting to be uncovered." },
    { "In the land of the Nords, the frost can bite and the fire can warm." },
    { "The lore of Tamriel is vast and filled with tales of bravery and folly." },
    { "The Companions offer strength in numbers and camaraderie in battle." },
    { "The Shouts of the Dragonborn can echo through the mountains." },
    { "The Throat of the World is the highest peak in Skyrim, home to the Greybeards." },
    { "A true warrior never backs down from a fight." },
    { "The Song of the Alchemist tells of potions that can heal and harm." },
    { "Nature holds the secrets of life and death." },
    { "Dwemer technology is a marvel, but shrouded in mystery." },
    { "The Elder Scrolls are powerful artifacts that can alter time and destiny." },
    { "Argonians are a resilient people, adapted to life in the marshes." },
    { "The influence of the Thalmor can be felt throughout Skyrim." },
    { "Even the strongest among us have weaknesses." },
    { "The path of the assassin is a lonely one." },
    { "The Dark Brotherhood awaits those who seek its dark gifts." },
    { "There are few things more dangerous than a wounded beast." },
    { "The trials of the Dragonborn are the stuff of legends." },
    { "Knowledge is power, but wisdom is the key." },
    { "Trust is a rare commodity in the world of Skyrim." },
    { "Those who fear the dark often hide from their own shadows." },
    { "To walk the path of the mage is to embrace the unknown." },
    { "Some believe the moons of Nirn are watching over us." },
    { "The time of dragons has returned, and with it, great change." },
    { "Death is not the end, but a new beginning." },
    { "The dragons of Skyrim are a constant threat to the people and their lands." },
    { "Skyrim is home to many dangers, both natural and unnatural." },
    { "The Nords believe that death is not the end, but the beginning of another journey." },
    { "A Nord's home is their most sacred place." },
    { "The Throat of the World is the tallest mountain in Skyrim." },
    { "Many Nords revere the ancient dragons as divine beings." },
    { "The Greybeards are masters of the Voice, capable of great power." },
    { "The civil war in Skyrim has left deep scars on its people." },
    { "Alchemy is the art of combining ingredients to create powerful potions." },
    { "Skooma is a dangerous drug, beloved by many but harmful to the mind." },
    { "Many fear the vampire clans that lurk in the shadows." },
    { "The Companions are a group of skilled warriors based in Whiterun." },
    { "Magic is a powerful tool, but it can also be dangerous in the wrong hands." },
    { "The Daedric Princes are ancient and powerful beings." },
    { "The Shouts of the Dragonborn are unique and powerful abilities." },
    { "Many treasures are hidden within the ruins of Skyrim." },
    { "The College of Winterhold is a place of learning and magic." },
    { "Mammoths and giants roam the tundra of Skyrim." },
    { "The civil war has torn families apart across Skyrim." },
    { "The ancient Dwemer left behind many mysteries." },
    { "The Blades are a group dedicated to protecting the Dragonborn." },
    { "The Daedra often tempt mortals with power in exchange for their souls." },
    { "The ancient Nord tombs are filled with both treasure and danger." },
    { "Some believe the gods watch over Skyrim, while others do not." },
    { "The Thieves Guild operates in the shadows of Riften." },
    { "Many Nords tell tales of heroes from ages past." },
    { "The Imperials have a strong presence in Skyrim." },
    { "The land of Skyrim is rich with history and culture." },
    { "The ancient Dragonborn were revered for their power." },
    { "Forsworn are known to attack travelers in the Reach." },
    { "Skyrim is a land of beauty and danger." },
    { "The way of the Voice is taught only to those deemed worthy." },
    { "Some say the Wolf is the symbol of the Nord spirit." },
    { "Nord warriors honor their ancestors in many ways." },
    { "The mountains of Skyrim hold secrets that only the brave discover." },
    { "The land is filled with ruins that tell stories of the past." },
    { "Many fear the wrath of the dragons as they return to Skyrim." },
    { "The wind is a constant companion in the cold of Skyrim." },
    { "A Nord's honor is more important than their life." },
    { "The gods often test the resolve of mortals." },
    { "There are many paths to glory, but few to redemption." },
    { "The ancient stones of Skyrim hold great power." },
    { "Nord legends speak of great battles against dragons." },
    { "The warmth of a fire can bring comfort in the harsh cold." },
    { "Some believe that the spirits of the dead linger in Skyrim." },
    { "The wilds of Skyrim are home to many dangerous creatures." },
    { "Skyrim's history is written in blood and valor." },
    { "Dwarven ruins are filled with strange machines and secrets." },
    { "The heart of a Nord beats for freedom and honor." },
    { "Some travel to Skyrim seeking adventure, others seek power." },
    { "The shadows of the past can still affect the present." },
    { "Some quests lead to glory, while others lead to despair." },
    { "The Dragonborn must prove themselves worthy of their power." },
    { "The art of war is as old as Skyrim itself." },
    { "The path of the Dragonborn is fraught with challenges." },
    { "The winds of change blow through Skyrim, carrying stories of hope." },
    { "Legends say that the first Dragonborn was a hero of great power." },
    { "The Dark Brotherhood operates in secrecy, carrying out contracts for gold." },
    { "The cities of Skyrim are bustling with trade and intrigue." },
    { "Many seek the path of the Thief, but few find true success." },
    { "The ruins of ancient civilizations can be found throughout Skyrim." },
    { "Each Nordic hold has its own unique customs and traditions." },
    { "The wolves of Skyrim are both beautiful and deadly." },
    { "The powerful shout known as Unrelenting Force can send foes flying." },
    { "Many believe that the afterlife awaits those who die honorably." },
    { "The rituals of the Nords honor their ancestors in many ways." },
    { "The College of Winterhold is a sanctuary for mages and scholars." },
    { "The spirits of the land are said to guide those who listen." },
    { "Nord warriors are known for their bravery and strength in battle." },
    { "Sailing the seas can be a dangerous affair for any adventurer." },
    { "The ashes of the past can fuel the flames of the present." },
    { "Some say that dragons are merely myths, but they know the truth." },
    { "The ancient shrines scattered across Skyrim hold secrets of the past." },
    { "A skilled archer can strike with deadly precision from afar." },
    { "The civil war has created rifts between families and friends." },
    { "There are tales of great treasures hidden in the mountains." },
    { "Some of the most powerful warriors are forged in the heat of battle." },
    { "The Bard's College in Solitude is known for its rich traditions." },
    { "Those who venture into the wilds must be prepared for anything." },
    { "The Dragonborn has the power to change the fate of Skyrim." },
    { "The war between the Aldmeri Dominion and the Empire affects all." },
    { "The forests of Skyrim are alive with the sounds of nature." },
    { "There are few things more dangerous than a desperate man." },
    { "The trials of the Dragonborn test both body and spirit." },
    { "Some say the Throat of the World is the home of the gods." },
    { "The balance of power in Skyrim shifts like the wind." },
    { "Many believe that knowledge is the greatest power of all." },
    { "Nordic traditions are steeped in tales of glory and honor." },
    { "The sands of time can bury even the greatest of heroes." },
    { "Magic can be a double-edged sword; use it wisely." },
    { "The Dragonborn's destiny is intertwined with the fate of Skyrim." },
    { "There are those who seek to control dragons for their own ends." },
    { "Beneath the surface of the world lies the unknown." },
    { "Skyrim is filled with ancient secrets waiting to be uncovered." },
    { "A warrior's heart is as strong as their blade." },
    { "The landscapes of Skyrim can change in the blink of an eye." },
    { "Dangers lurk in the shadows of every corner." },
    { "The power of the Thu'um can bring the strongest foes to their knees." },
    { "The legacy of the Dragonborn will echo through the ages." },
    { "Some believe that the mountains hold the spirits of ancient giants." },
    { "The fire of a dragon can melt even the strongest steel." },
    { "Every hero begins their journey with a single step." },
    { "In Skyrim, trust is a rare and valuable commodity." },
    { "The beauty of the land is matched only by its dangers." },
    { "To truly understand Skyrim, one must walk its roads." },
    { "The tales of old speak of great heroes and their legendary deeds." },
    { "To survive in Skyrim, one must learn to adapt." },
    { "The whispers of the past can guide the brave." },
    { "Skyrim's history is written by those who dare to shape it." },
    { "Many seek the wisdom of the ancient ones." },
    { "A true Nord never backs down from a challenge." },
    { "In Skyrim, legends are born in fire and steel." },
    { "The Khajiit are known for their skills in stealth and agility." },
    { "The world is full of dangers, but also opportunities for those brave enough." },
    { "Every creature in Skyrim has its place in the great tapestry of life." },
    { "The might of the Nords is legendary, forged in the fires of battle." },
    { "Ruin and glory are often two sides of the same coin." },
    { "The path of the mage is fraught with peril, but also great power." },
    { "Some say the gods have chosen the Dragonborn to restore balance." },
    { "Those who defy fate may find themselves on a treacherous path." },
    { "The Song of Pelinal tells of a hero's struggle against darkness." },
    { "Beneath the waves lie ancient treasures waiting to be discovered." },
    { "The frostbite spiders of Skyrim are as deadly as they are feared." },
    { "Happiness is fleeting, but the memory of a good fight lingers." },
    { "The Alchemist's art can heal or harm, depending on the wielder." },
    { "In the heart of every Nord lies a fire that cannot be extinguished." },
    { "The many paths of Skyrim offer adventure for the daring." },
    { "Honor is the soul of a warrior; without it, they are lost." },
    { "Many of the ancient ruins are said to be haunted by restless spirits." },
    { "A true friend is worth more than gold in a land of betrayal." },
    { "To wield a weapon is to embrace the call of destiny." },
    { "Even the smallest creature can hold great significance in the balance." },
    { "Wisdom often comes from unexpected places." },
    { "The dragonborn carries the burden of both power and responsibility." },
    { "A single act of kindness can ripple through the ages." },
    { "The flames of the past can light the way to the future." },
    { "In Skyrim, loyalty is as precious as any gem." },
    { "The spirits of the fallen watch over their kin." },
    { "Magic is a tool; how you use it defines your destiny." },
    { "The challenge of the unknown can reveal your true strength." },
    { "A warrior's courage is tested in times of great peril." },
    { "The road less traveled can lead to great discoveries." },
    { "The shadows hide many secrets, but also many dangers." },
    { "The ancestors guide the Nords in times of strife." },
    { "The songs of the bards tell tales of bravery and adventure." },
    { "In the depths of despair, hope can shine the brightest." },
    { "The time of the Dragonborn has come, and destiny awaits." },
    { "To conquer fear is to embrace the essence of life." },
    { "The world is a canvas, and every action paints a story." },
    { "The fires of war can forge new alliances." },
    { "Every decision has consequences that echo through time." },
    { "Skyrim is a land of contrasts, beauty intertwined with danger." },
    { "The Thieves Guild is both feared and respected in equal measure." },
    { "The essence of life is the journey, not just the destination." },
    { "To listen is as important as to speak." },
    { "The whispers of the past can shape the future." },
    { "Friendship can be as powerful as any blade." },
    { "The Dragonborn's journey is one of trials and triumph." },
    { "The strength of the heart is unmatched by any weapon." },
    { "To challenge the status quo is to embrace change." },
    { "The bonds of family are forged in the fires of hardship." },
    { "The past may fade, but its lessons endure." },
    { "In Skyrim, the line between hero and villain is often blurred." },
    { "To understand others, one must first understand oneself." },
    { "The beauty of Skyrim is both inspiring and haunting." },
    { "Victory is sweeter when earned through struggle." },
    { "The bards sing of heroes, but the true heroes are those who act in silence." },
    { "The dragons once ruled the skies; their return signals a new age." },
    { "Skyrim's beauty is matched only by its peril." },
    { "All things must come to an end, even the mightiest of foes." },
    { "There is a fine line between wisdom and madness." },
    { "The night is dark and full of terrors." },
    { "In Skyrim, the mountains hold secrets older than time." },
    { "Each blade of grass has its own story." },
    { "The sound of a blade being drawn can silence a thousand words." },
    { "The power of the Thu'um lies not just in the voice, but in the heart." },
    { "True magic comes not from books, but from the soul." },
    { "A clever thief can steal anything, including the hearts of the unsuspecting." },
    { "Every hero's journey begins with a single step." },
    { "The coldest winter brings the warmest fires." },
    { "The greatest battles are fought within." },
    { "The future is a canvas; paint it with your actions." },
    { "Every creature has a purpose; some are just harder to find." },
    { "In the world of men, dragons are but myths." },
    { "The journey is just as important as the destination." },
    { "Legends are born from the fires of truth." },
    { "Even the smallest act of kindness can change the world." },
    { "In Skyrim, trust is as rare as gold." },
    { "The choices we make shape our destiny." },
    { "A wise warrior knows when to fight and when to flee." },
    { "Every snowflake is unique, just like every soul." },
    { "Fear is a powerful ally, but a dangerous master." },
    { "Skyrim's past is written in the stones of its ruins." },
    { "The whispers of the past can guide us in the present." },
    { "A flame can both warm and consume." },
    { "To travel is to learn; to learn is to grow." },
    { "In the heart of every storm lies a calm eye." },
    { "To conquer oneself is the greatest victory." },
    { "The fire of ambition can illuminate the darkest paths." },
    { "Life is a series of quests, each with its own rewards." },
    { "In every shadow, there is a glimmer of light." },
    { "The strength of a warrior is only as strong as their resolve." },
    { "In times of peace, prepare for war." },
    { "A true friend will stand by you even in the darkest of times." },
    { "Even the longest journey begins with a single step." },
    { "Hope is the light that guides us through the darkest nights." },
    { "A heart filled with hope can conquer any fear." },
    { "Every end is but a new beginning." },
    { "In Skyrim, the winds of fate blow where they will." },
    { "The strongest bonds are forged in the fires of adversity." },
    { "Wisdom comes not from age, but from experience." },
    { "The past cannot be changed, but the future is yours to shape." },
    { "A hero is not defined by their victories, but by their choices." },
    { "In the silence of the night, the truth can be heard." },
    { "The sun will rise again, no matter how dark the night." },
    { "In every battle, there is a lesson to be learned." },
    { "Legends are not born; they are made." },
    { "In the shadows, we find our strength." },
    { "Every quest is a chance to discover who we truly are." },
    { "In the face of danger, courage shines brightest." },
    { "Skyrim teaches that every choice has a consequence." },
    { "Not all who wander are lost." },
    { "The right path is never the easiest." },
    { "The Throat of the World watches over us all." },
    { "Sometimes the greatest treasure is found in the journey." },
    { "Those who seek knowledge must be willing to pay its price." },
    { "What is dead may never die, but rises again." },
    { "The dragons return, and with them, the echoes of the past." },
    { "Time flows like water; we can only swim with it." },
    { "The most dangerous game is the one played with fate." },
    { "Your fate is not yet written." },
    { "The fiercest storms reveal the strongest of hearts." },
    { "The hidden paths are often the most rewarding." },
    { "A good leader listens to the whispers of the wind." },
    { "Truth can be a bitter pill to swallow." },
    { "In the heat of battle, the mind must remain clear." },
    { "A shadow can hide many truths." },
    { "Every story has two sides; listen closely." },
    { "A dragon's roar echoes through the ages." },
    { "The whispers of the ancients guide the brave." },
    { "The heart of a warrior beats for honor." },
    { "Change is the only constant in Skyrim." },
    { "Behind every mask lies a hidden truth." },
    { "The journey teaches lessons the destination cannot." },
    { "Even the smallest flame can light the darkest night." },
    { "The past is a shadow; the future is a light." },
    { "In the end, we are all dust in the wind." },
    { "Not all battles are fought with swords." },
    { "A wise man knows he knows nothing." },
    { "The mountains echo the cries of the lost." },
    { "The true strength of a warrior lies in their heart." },
    { "Every stone has a story to tell." },
    { "The gods watch over those who seek their favor." },
    { "In the heart of the storm lies calm." },
    { "A single spark can ignite a revolution." },
    { "Hope is the anchor in the stormy seas." },
    { "The strongest chains are those forged in the fire of loyalty." },
    { "In Skyrim, one must be both hunter and hunted." },
    { "The greatest victories often come at the highest cost." },
    { "Every wound tells a story." },
    { "A journey of a thousand miles begins with a single step." },
    { "The heart of a dragon beats within us all." },
    { "Destiny is a fickle mistress." },
    { "True power is found in unity." },
    { "The light of dawn brings new hope." },
    { "Legends are written by those who dare to act." },
    { "Even the mightiest walls can crumble." },
    { "Wisdom lies in the heart of the humble." },
    { "The call of adventure is hard to resist." },
    { "Strength is not always brute force." },
    { "To understand the world, one must listen." },
    { "The silence of the night is filled with whispers." },
    { "Every dragon has its day." },
    { "The path of the hero is fraught with peril." },
    { "In the darkest hour, the light shines brightest." },
    { "The journey shapes the hero as much as the destination." },
    { "The strongest weapon is a kind heart." },
    { "The blood of the dragon flows through you." },
    { "A true hero fights for those who cannot." },
}
  }
  math.randomseed(os.time())
  return footer_quotes[math.random(#footer_quotes)]
end

return {
  "nvimdev/dashboard-nvim",
  opts = function(_, opts)
    -- Ensure the random seed is initialized for randomness
    math.randomseed(os.time())

    local logo = string.format(
      [[
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡇⠀⠀⠀⠀⢸⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡿⠙⠀⠀⠀⠀⠋⢿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⠇⠀⣺⠀⠀⠀⠀⠸⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⡟⠀⢀⣾⣷⣖⠊⠀⠀⢻⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⡃⠀⣸⠏⠉⠈⠻⣆⠀⠸⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⡀⠀⠀⠀⢀⣠⡴⠇⠀⣀⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣿⣻⡃⠙⠂⢀⣾⡟⠉⠀⠀⠐⠉⢙⣿⣾⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⡿⠀⢀⡀⠘⣿⣧⡀⠀⠀⢀⡀⠀⣿⣿⣽⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⡿⣷⣿⣄⣤⢿⣾⣿⣿⣿⣰⣷⣿⢤⣤⣾⣿⣯⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣯⣿⣿⣽⣿⣿⣿⣿⣽⣿⣿⣿⡿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⠾⣿⡿⣿⣿⣿⣿⣟⣯⠿⣿⣽⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⠃⠈⠇⠈⢿⣿⡇⠸⠁⢐⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⡀⠀⠀⠀⠈⣿⡇⠀⠀⢀⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣶⡀⠀⢀⣿⡇⠠⣴⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⠄⢀⣾⠋⠀⠐⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⠂⢺⡇⠀⠀⠀⠙⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠅⢀⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣶⣶⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

    [ %s ]
    ]],
      get_random_header_quote()
    )
    -- Increase the number of newlines before and after the logo
    logo = string.rep("\n", 2) .. logo .. string.rep("\n", 2)
    opts.config.header = vim.split(logo, "\n")
    opts.config.footer = function()
      local stats = require("lazy").stats()
      local ms = (math.floor(stats.startuptime * 100 + 0.5) / 100)
      local random_quote = get_random_footer_quote()
      local footer = {
        "⚡ Neovim loaded " .. stats.loaded .. "/" .. stats.count .. " plugins in " .. ms .. "ms",
        "",
        random_quote[1],
        "",
      }
      return footer
    end
    return opts
  end,
}
